"""Command term that generates a walk path for the robot to track.

On deployment, a walk path planner runs onboard and knows the planned path
relative to the robot (via odometry). To match that interface, the policy
observes a short horizon of upcoming path poses expressed in the robot's
own yaw frame (see :attr:`PathCommand.waypoints`) — never world-frame
state. Paths are regenerated mid-episode from the robot's current pose,
mimicking a planner that replans on the fly around obstructions.

For rewards, the term derives a desired body-frame twist from the path
(reference twist plus a proportional correction toward the reference
pose). This keeps the well-tuned velocity-task reward structure — twist
tracking, command-magnitude gating, gait clock — working unchanged. The
desired twist is *not* observed by the actor; it only shapes rewards.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import numpy as np
import torch

from mjlab.entity import Entity
from mjlab.managers.command_manager import CommandTerm, CommandTermCfg
from mjlab.utils.lab_api.math import wrap_to_pi

if TYPE_CHECKING:
  from mjlab.envs.manager_based_rl_env import ManagerBasedRlEnv
  from mjlab.viewer.debug_visualizer import DebugVisualizer


class PathCommand(CommandTerm):
  """Samples a feasible walk path and exposes it as a tracking target.

  A path is a dense sequence of (x, y, heading) world-frame poses with an
  associated body-frame reference twist per step. Paths are generated by
  sampling piecewise-constant twists (within ``cfg.ranges``) and
  integrating a planar unicycle/holonomic model from the robot's pose at
  resample time, so every path is dynamically feasible for the sampled
  velocity ranges.
  """

  cfg: PathCommandCfg

  def __init__(self, cfg: PathCommandCfg, env: ManagerBasedRlEnv):
    super().__init__(cfg, env)
    self.robot: Entity = env.scene[cfg.entity_name]

    self._dt = env.step_dt
    # The path must outlast the resample timer plus the observation
    # lookahead so waypoint queries never run off the end.
    horizon = cfg.resampling_time_range[1] + max(cfg.lookahead_times) + 1.0
    self._num_steps = int(round(horizon / self._dt)) + 1
    self._num_segments = int(np.ceil(horizon / cfg.segment_duration_range[0])) + 1
    self._lookahead_steps = torch.tensor(
      [int(round(t / self._dt)) for t in cfg.lookahead_times],
      device=self.device,
      dtype=torch.long,
    )

    N = self._num_steps
    K = len(cfg.lookahead_times)
    # World-frame reference states, one per control step along the path.
    self.ref_pos_w = torch.zeros(self.num_envs, N, 2, device=self.device)
    self.ref_heading_w = torch.zeros(self.num_envs, N, device=self.device)
    # Body-frame (path-heading-frame) reference twist at each step.
    self.ref_twist_b = torch.zeros(self.num_envs, N, 3, device=self.device)
    # Index of the current reference state along the path.
    self.path_step = torch.zeros(self.num_envs, device=self.device, dtype=torch.long)
    # Envs whose freshly sampled path still needs to be anchored to the
    # robot's pose (deferred until kinematics are fresh, see compute()).
    self._needs_rebase = torch.zeros(
      self.num_envs, dtype=torch.bool, device=self.device
    )
    # Path steps to advance per compute() call, derived from the dt the
    # env passes in (0 for the post-reset compute call).
    self._advance_steps = 1

    # Outputs.
    self.twist_command_b = torch.zeros(self.num_envs, 3, device=self.device)
    self.waypoints_b = torch.zeros(self.num_envs, K, 4, device=self.device)
    self.is_standing_env = torch.zeros(
      self.num_envs, dtype=torch.bool, device=self.device
    )

    self.metrics["error_pos"] = torch.zeros(self.num_envs, device=self.device)
    self.metrics["error_heading"] = torch.zeros(self.num_envs, device=self.device)

  @property
  def command(self) -> torch.Tensor:
    """Desired body-frame twist (vx, vy, wz) derived from the path.

    Used by rewards and command-magnitude gates. Not an actor observation.
    """
    return self.twist_command_b

  @property
  def waypoints(self) -> torch.Tensor:
    """Lookahead path poses relative to the robot, flattened to [B, K*4].

    Each waypoint is (dx, dy, cos(dheading), sin(dheading)) in the robot's
    yaw frame — the same quantities an onboard planner can supply from its
    own path and odometry, so this is deployment-safe as an actor input.
    """
    return self.waypoints_b.flatten(start_dim=1)

  def _update_metrics(self) -> None:
    max_command_time = self.cfg.resampling_time_range[1]
    max_command_step = max_command_time / self._env.step_dt
    batch = torch.arange(self.num_envs, device=self.device)
    ref_pos = self.ref_pos_w[batch, self.path_step]
    ref_heading = self.ref_heading_w[batch, self.path_step]
    pos_error = torch.norm(ref_pos - self.robot.data.root_link_pos_w[:, :2], dim=-1)
    heading_error = torch.abs(wrap_to_pi(ref_heading - self.robot.data.heading_w))
    self.metrics["error_pos"] += pos_error / max_command_step
    self.metrics["error_heading"] += heading_error / max_command_step

  def compute(self, dt: float) -> None:
    # Paths sampled during env reset could not read the robot pose (derived
    # kinematics are stale until the env calls sim.forward(), which happens
    # right before this method). Anchor them now, before metrics are
    # accumulated. The env calls compute(dt=0.0) once after reset, so the
    # per-call path advance is derived from dt rather than fixed at 1.
    self._advance_steps = int(round(dt / self._dt))
    self._rebase_pending_paths()
    super().compute(dt)

  def _resample_command(self, env_ids: torch.Tensor) -> None:
    """Sample new path twist profiles for the given environments.

    Called on episode reset and on the resample timer. Mid-episode calls
    model a planner replanning from wherever the robot currently is. Only
    the twist profile is sampled here; integrating it from the robot's
    current pose is deferred to :meth:`_rebase_pending_paths` because the
    robot's derived kinematics may be stale during env reset.
    """
    E = len(env_ids)
    S = self._num_segments
    N = self._num_steps
    dt = self._dt

    r = torch.empty(E, device=self.device)

    # Piecewise-constant segment twists.
    twists = torch.empty(E, S, 3, device=self.device)
    twists[..., 0].uniform_(*self.cfg.ranges.lin_vel_x)
    twists[..., 1].uniform_(*self.cfg.ranges.lin_vel_y)
    twists[..., 2].uniform_(*self.cfg.ranges.ang_vel_z)

    # Some segments come to a stop so the policy learns to halt and
    # restart mid-path (a replanned path can require both).
    standing_seg = torch.rand(E, S, device=self.device) < self.cfg.rel_standing_segments
    twists[standing_seg] = 0.0

    # Some environments stand in place for the whole path.
    self.is_standing_env[env_ids] = r.uniform_(0.0, 1.0) <= self.cfg.rel_standing_envs
    twists[self.is_standing_env[env_ids]] = 0.0

    durations = torch.empty(E, S, device=self.device).uniform_(
      *self.cfg.segment_duration_range
    )
    seg_end_times = torch.cumsum(durations, dim=1)  # [E, S]
    t = torch.arange(N, device=self.device, dtype=torch.float32) * dt  # [N]
    seg_idx = torch.searchsorted(seg_end_times, t.expand(E, N).contiguous(), right=True)
    seg_idx = seg_idx.clamp(max=S - 1)  # [E, N]
    twist_steps = torch.gather(twists, 1, seg_idx.unsqueeze(-1).expand(E, N, 3))

    self.ref_twist_b[env_ids] = twist_steps
    self.path_step[env_ids] = 0
    self._needs_rebase[env_ids] = True

  def _rebase_pending_paths(self) -> None:
    """Integrate freshly sampled twist profiles from the robots' poses."""
    env_ids = self._needs_rebase.nonzero(as_tuple=False).flatten()
    if len(env_ids) == 0:
      return
    self._needs_rebase[env_ids] = False

    E = len(env_ids)
    dt = self._dt
    twist_steps = self.ref_twist_b[env_ids]  # [E, N, 3]

    # Integrate the planar model from the robot's current pose. State at
    # step k is the pose *before* applying twist k.
    pos0 = self.robot.data.root_link_pos_w[env_ids, :2]  # [E, 2]
    heading0 = self.robot.data.heading_w[env_ids]  # [E]

    w = twist_steps[..., 2]
    dheading = torch.cumsum(w * dt, dim=1)
    heading = heading0.unsqueeze(1) + torch.cat(
      [torch.zeros(E, 1, device=self.device), dheading[:, :-1]], dim=1
    )  # [E, N]

    cos_h = torch.cos(heading)
    sin_h = torch.sin(heading)
    vx = twist_steps[..., 0]
    vy = twist_steps[..., 1]
    dx = (vx * cos_h - vy * sin_h) * dt
    dy = (vx * sin_h + vy * cos_h) * dt
    x = pos0[:, 0:1] + torch.cat(
      [torch.zeros(E, 1, device=self.device), torch.cumsum(dx, dim=1)[:, :-1]], dim=1
    )
    y = pos0[:, 1:2] + torch.cat(
      [torch.zeros(E, 1, device=self.device), torch.cumsum(dy, dim=1)[:, :-1]], dim=1
    )

    self.ref_pos_w[env_ids] = torch.stack([x, y], dim=-1)
    self.ref_heading_w[env_ids] = heading

  def _update_command(self) -> None:
    """Advance along the path and refresh the command outputs."""
    # Mid-episode resamples (replans) happen between _update_metrics and
    # this call; anchor them before advancing.
    self._rebase_pending_paths()
    self.path_step = (self.path_step + self._advance_steps).clamp(
      max=self._num_steps - 1
    )
    self._compute_outputs()

  def _compute_outputs(self) -> None:
    batch = torch.arange(self.num_envs, device=self.device)
    i = self.path_step

    ref_pos = self.ref_pos_w[batch, i]  # [B, 2]
    ref_heading = self.ref_heading_w[batch, i]  # [B]
    ref_twist = self.ref_twist_b[batch, i]  # [B, 3]

    robot_pos = self.robot.data.root_link_pos_w[:, :2]
    robot_heading = self.robot.data.heading_w

    # Reference linear velocity in world frame.
    cos_r = torch.cos(ref_heading)
    sin_r = torch.sin(ref_heading)
    v_ref_w_x = ref_twist[:, 0] * cos_r - ref_twist[:, 1] * sin_r
    v_ref_w_y = ref_twist[:, 0] * sin_r + ref_twist[:, 1] * cos_r

    # Desired velocity: feedforward reference plus proportional pull back
    # toward the reference pose, rotated into the robot's yaw frame.
    v_des_w_x = v_ref_w_x + self.cfg.pos_gain * (ref_pos[:, 0] - robot_pos[:, 0])
    v_des_w_y = v_ref_w_y + self.cfg.pos_gain * (ref_pos[:, 1] - robot_pos[:, 1])
    cos_b = torch.cos(robot_heading)
    sin_b = torch.sin(robot_heading)
    v_des_b_x = cos_b * v_des_w_x + sin_b * v_des_w_y
    v_des_b_y = -sin_b * v_des_w_x + cos_b * v_des_w_y

    w_des = ref_twist[:, 2] + self.cfg.heading_gain * wrap_to_pi(
      ref_heading - robot_heading
    )

    self.twist_command_b[:, 0] = v_des_b_x.clamp(*self.cfg.ranges.lin_vel_x)
    self.twist_command_b[:, 1] = v_des_b_y.clamp(*self.cfg.ranges.lin_vel_y)
    self.twist_command_b[:, 2] = w_des.clamp(*self.cfg.ranges.ang_vel_z)

    # Lookahead waypoints in the robot's yaw frame.
    idx = (i.unsqueeze(1) + self._lookahead_steps.unsqueeze(0)).clamp(
      max=self._num_steps - 1
    )  # [B, K]
    wp_pos = torch.gather(
      self.ref_pos_w, 1, idx.unsqueeze(-1).expand(-1, -1, 2)
    )  # [B, K, 2]
    wp_heading = torch.gather(self.ref_heading_w, 1, idx)  # [B, K]

    dp_w = wp_pos - robot_pos.unsqueeze(1)  # [B, K, 2]
    cos_b = cos_b.unsqueeze(1)
    sin_b = sin_b.unsqueeze(1)
    self.waypoints_b[..., 0] = cos_b * dp_w[..., 0] + sin_b * dp_w[..., 1]
    self.waypoints_b[..., 1] = -sin_b * dp_w[..., 0] + cos_b * dp_w[..., 1]
    dheading = wrap_to_pi(wp_heading - robot_heading.unsqueeze(1))
    self.waypoints_b[..., 2] = torch.cos(dheading)
    self.waypoints_b[..., 3] = torch.sin(dheading)

  # Visualization.

  def _debug_vis_impl(self, visualizer: DebugVisualizer) -> None:
    """Draw the remaining path, lookahead waypoints, and tracking error."""
    env_indices = visualizer.get_env_indices(self.num_envs)
    if not env_indices:
      return

    stride = max(1, int(round(self.cfg.viz.point_spacing_s / self._dt)))
    ref_pos = self.ref_pos_w.cpu().numpy()
    path_steps = self.path_step.cpu().numpy()
    lookahead = self._lookahead_steps.cpu().numpy()
    robot_pos = self.robot.data.root_link_pos_w.cpu().numpy()
    z = self.cfg.viz.z_offset

    for batch in env_indices:
      i = int(path_steps[batch])
      # Remaining path as a dotted line of small spheres.
      for j in range(i, self._num_steps, stride):
        p = ref_pos[batch, j]
        visualizer.add_sphere(
          center=np.array([p[0], p[1], z]),
          radius=0.01,
          color=(0.2, 0.4, 1.0, 0.5),
        )
      # Lookahead waypoints the policy currently observes.
      for k in lookahead:
        j = min(i + int(k), self._num_steps - 1)
        p = ref_pos[batch, j]
        visualizer.add_sphere(
          center=np.array([p[0], p[1], z]),
          radius=0.025,
          color=(1.0, 0.6, 0.0, 0.9),
        )
      # Current reference pose and the robot's offset from it.
      p_ref = ref_pos[batch, i]
      visualizer.add_sphere(
        center=np.array([p_ref[0], p_ref[1], z]),
        radius=0.03,
        color=(0.0, 1.0, 0.2, 0.9),
      )
      visualizer.add_arrow(
        start=np.array([robot_pos[batch, 0], robot_pos[batch, 1], z]),
        end=np.array([p_ref[0], p_ref[1], z]),
        color=(0.0, 1.0, 0.2, 0.6),
        width=0.01,
      )


@dataclass(kw_only=True)
class PathCommandCfg(CommandTermCfg):
  """Configuration for the path tracking command."""

  entity_name: str

  rel_standing_envs: float = 0.0
  """Fraction of environments whose path is standing in place."""

  rel_standing_segments: float = 0.1
  """Probability that an individual path segment is a full stop."""

  segment_duration_range: tuple[float, float] = (2.0, 4.0)
  """Duration range in seconds of each constant-twist path segment."""

  lookahead_times: tuple[float, ...] = (0.2, 0.5, 1.0, 2.0)
  """Path-time offsets in seconds of the waypoints exposed to the policy."""

  pos_gain: float = 1.0
  """Proportional gain (1/s) pulling the desired twist toward the path."""

  heading_gain: float = 0.5
  """Proportional gain on heading error for the desired yaw rate."""

  @dataclass
  class Ranges:
    """Twist sampling ranges used to generate path segments.

    Field names match :class:`UniformVelocityCommandCfg.Ranges` so the
    ``commands_vel`` curriculum can mutate them unchanged.
    """

    lin_vel_x: tuple[float, float]
    lin_vel_y: tuple[float, float]
    ang_vel_z: tuple[float, float]

  ranges: Ranges

  @dataclass
  class VizCfg:
    """Visualization configuration."""

    z_offset: float = 0.02
    """Height above the ground at which path markers are drawn."""
    point_spacing_s: float = 0.25
    """Path-time spacing in seconds between drawn path points."""

  viz: VizCfg = field(default_factory=VizCfg)

  def build(self, env: ManagerBasedRlEnv) -> PathCommand:
    return PathCommand(self, env)

  def __post_init__(self):
    if not self.lookahead_times or any(t < 0.0 for t in self.lookahead_times):
      raise ValueError("lookahead_times must be non-empty and non-negative.")
