apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mjlab-logs
  namespace: mjlab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 50Gi
